### ISSUE TITLE
[Rust] Cargo.toml 添加依赖，cargo build 后，lsp-bridge 不能检测到该crate

### ISSUE THREAD

**Issue by nesteiner** [manateelazycat/lsp-bridge#229]
重现下代码  
开启 `lsp-bridge` 后，在 `Cargo.toml` 添加  
```toml
[dependencies]
walkdir = "2"
```
cargo build 后，返回到 `main.rs` ，type  `use walkdir` 发现途中没有补全选项，重启 `lsp-bridge` 之后可以使用了
